techitPlus-FE-team3/open_market_projerct

open-market/src/routes.tsx

- App.tsx RouterProvider 추가
- src > routes.tsx 생성
2023.11.23

:sparkles: [Feat] 라우터 기능 추가 #3

---

open-market/src/App.tsx
open-market/src/pages/Index.tsx
open-market/src/routes.tsx

- App.tsx RouterProvider 추가
- src > routes.tsx 생성
2023.11.23

✨ [Feat] 라우터 기능 추가 #3

---

open-market/src/pages/Login.tsx
open-market/src/routes.tsx

- 로그인 페이지 마크업 작업
- 로그인 페이지 라우트 연결
- 로그인 페이지 <Helmet> 에 title 속성 적용
2023.11.23

:lipstick:[Design] Login 페이지 마크업 작업 및 라우트 연결 #2

---

open-market/package-lock.json
open-market/package.json

- 폰트어썸 패키지 설치
- 구글 material UI 아이콘 설치
- 
[폰트어썸 사용법1](https://ssddo-story.tistory.com/15)
[폰트어썸 사용법2](https://www.daleseo.com/react-font-awesome/)
[구글 MUI 아이콘 사용법](https://www.daleseo.com/material-ui-icons/)
2023.11.23

[Feature] 폰트어썸 material UI 세팅 #1

---

open-market/src/App.tsx
open-market/src/layout/RootLayout.tsx
open-market/src/pages/Index.tsx
open-market/src/routes.tsx

- 메인페이지 마크업 작업
- 라우터 적용
- RootLayout 파일 생성 및 라우터 연결
2023.11.23

✨ [Feature] 라우터에 RootLayout 생성 및 연결, 💄 [Design] 메인페이지 마크업 작업 #3

---

open-market/src/pages/Login.tsx
open-market/src/pages/SignUp.tsx
open-market/src/routes.tsx

- SignUp 페이지 마크업 작업
- SignUp 페이지 라우트 추가
- 로그인 페이지에 SignUp 페이지 라우트 연결
2023.11.23

💄[Design] SignUp 페이지 마크업 작업 및 라우트 추가, 연결 #9

---

open-market/package-lock.json
open-market/package.json

- 폰트어썸 제거
- MUI 세팅 수정
2023.mm.dd

✨[Feat] 폰트어썸 material UI 세팅 #1 

---

open-market/src/pages/Login.tsx
open-market/src/pages/SignIn.tsx
open-market/src/routes.tsx

- Login을 SignIn으로 수정(Login.tsx, routes.tsx 수정)
2023.11.23

🚚[Rename] Login을 SignIn으로 수정 #2

---

open-market/package-lock.json
open-market/src/pages/Detail.tsx
open-market/src/routes.tsx

- 상품 상세 페이지 마크업 작업
- HTML 요소 나열
2023.11.23

💄 [Design] 상품 상세 페이지 마크업 작업 #6

---

open-market/src/pages/Index.tsx
open-market/src/pages/ProductUpdate.tsx
open-market/src/routes.tsx

- 상품 수정 페이지 마크업
- 라우터 연결
2023.11.23

:lipstick: [Design] 상품 수정 페이지 마크업 #16

---

open-market/src/pages/Index.tsx
open-market/src/pages/ProductEdit.tsx
open-market/src/pages/ProductUpdate.tsx
open-market/src/routes.tsx

- 컴포넌트명 수정 (productUpdate -> productEdit)
2023.11.23

🚚 [Rename] ProductUpdate 컴포넌트명 수정 #16

---

open-market/src/pages/UserUpdate.tsx
open-market/src/routes.tsx

- 회원정보 수정 페이지 마크업
- 회원정보 수정 페이지 라우트 추가 
2023.11.23

💄[Design] 회원정보수정 페이지 마크업 및 라우트 추가 #17

---

open-market/src/layout/Footer.tsx
open-market/src/layout/Header.tsx
open-market/src/layout/RootLayout.tsx

- 헤더 요소 나열
- 푸터 임시 데이터 배치
- 푸터 임시 스타일링
2023.11.23

💄 [Design] 헤더/푸터 요소 배치 #20

---

open-market/src/pages/Purchase.tsx
open-market/src/routes.tsx

- 구매 페이지 마크업 
- 라우터 연결
2023.11.23

:lipstick: [Design] 구매 페이지 마크업 #26

---

open-market/src/pages/ProductManage.tsx
open-market/src/routes.tsx

:lipstick: [Design] 상품 관리 페이지 마크업

---

open-market/src/pages/MyPage.tsx
open-market/src/routes.tsx

- 마이페이지 마크업
- 필요 요소 나열
- 접근성 및 웹 표준을 고려한 태그 선정
- 스타일링을 고려한 요소 묶음
2023.11.24

💄 [Design] 마이페이지 마크업#31

---

open-market/src/pages/UserProducts.tsx
open-market/src/routes.tsx

- 판매상품 관리 페이지 마크업
- 판매상품 관리 페이지 라우트 추가
2023.11.24

💄[Design] 판매상품 관리 페이지 마크업 #24

---

open-market/src/pages/UserOrders.tsx
open-market/src/routes.tsx

- 구매내역 페이지 마크업
- 구매내역 페이지 라우트 추가
2023.11.24

💄[Design] 구매내역 페이지 마크업 및 라우트 추가 #35

---

open-market/src/pages/Purchase.tsx
open-market/src/routes.tsx

💄 [Design] 구매페이지 마크업 수정#42

---

open-market/src/pages/UserOrders.tsx
open-market/src/routes.tsx

- 플레이 아이콘 피그마와 일치하게 수정
- 앨범 타이틀을 p태그에서 Link 태그로 바꾼 후 상세보기 버튼 삭제
- 다운로드 버튼에 텍스트 추가
- 플레이스 홀더 수정
- 충돌 해결
2023.11.27

[Design] 구매 내역 페이지 마크업 수정 #54

---

open-market/package-lock.json
open-market/src/pages/Detail.tsx
open-market/src/pages/MyPage.tsx
open-market/src/routes.tsx

- 피그마 디자인 수정에 따른 제품 상세 페이지(재생 페이지) 마크업 수정
2023.11.27

💄 [Design] 상품 상세 페이지 마크업 수정 #57

---

open-market/src/pages/UserProducts.tsx
open-market/src/routes.tsx

- 플레이 아이콘 피그마와 일치하게 수정
- 공백 추가
- Helmet title 수정
- 충돌 해결
2023.11.27

💄[Design] Re: 판매 관리 페이지 마크업 수정 #51

---

open-market/src/pages/UserOrders.tsx
open-market/src/routes.tsx

- 플레이 아이콘 피그마와 일치하게 수정
- 앨범 타이틀을 p태그에서 Link 태그로 바꾼 후 상세보기 버튼 삭제
- 다운로드 버튼에 텍스트 추가
- 플레이스 홀더 수정
- 충돌 해결
2023.11.27

💄[Design] Re: 구매 내역 페이지 마크업 수정 #54

---

open-market/src/pages/UserUpdate.tsx
open-market/src/routes.tsx

- title 영문으로 수정
- 취소 버튼 Link 태그로 수정
- 충돌 해결
2023.11.27

💄[Design] 회원 정보 수정 페이지 마크업 수정 #66

---

open-market/src/pages/MyPage.tsx
open-market/src/routes.tsx

- 마이페이지 헬멧 추가
- 버튼 태그 링크 태그로 수정
2023.11.27

🐛 [Fix] 마이페이지 부적절한 태그 등 수정 #68

---

open-market/package-lock.json
open-market/src/pages/ProductRegistration.tsx
open-market/src/utils/uploadFile.ts

- 음악 / 이미지 파일 업로드 유틸함수 생성
- 상품등록 기능 구현
2023.11.29

✨ [Feat] 상품 등록 기능 구현 #72

---

open-market/src/pages/MyPage.tsx
open-market/src/utils/TokenRefresh.ts

- utils 폴더 생성 후 토큰 재발행 파일 및 코드 추가
`import { refreshToken } from './utils/refreshToken';
const someFunction = async () => {
try {
const newAccessToken = await refreshToken();
console.log('New access token:', newAccessToken);
// 새 토큰을 사용하여 추가 작업 수행
} catch (error) {
console.error('Error while refreshing token:', error);
// 에러 핸들링 (예: 로그아웃 처리 등)
}
};`
필요한 기능에서 호출하는 상황에 따라 개선 필요
2023.11.29

✨ [Feat] 토큰 리프레시 기능 구현 #85

---

open-market/src/pages/SignUp.tsx

- 회원가입 페이지 이메일 입력칸 옆 '중복확인' 버튼 생성
- 이메일 중복 확인 함수 생성
- 이메일 중복 확인 상태 생성 및 중복 확인 체크 여부 관리
- 이메질 중복 여부에 따른 메시지 표시 기능 구현
`	const [emailCheck, setEmailCheck] = useState({
checked: false,
valid: false,
message: "",
});
`
이와 같이 체크여부, 유효한 이메일 여부를 같이 상태로 관리하면서 체크가 안되었거나 유효한 이메일이 아닌 경우 다음 input으로 진행되지 않게 하는 등의 인터렉션을 이후 개발이 가능할 것으로 예상.
2023.11.29

✨[Feat] 회원가입 단계에서 이메일 중복 확인 기능 구현 #93

---

open-market/src/pages/ProductManage.tsx

✨ [Feature] 상품 삭제 기능 구현

---

open-market/src/pages/SignIn.tsx
open-market/src/pages/SignUp.tsx

- 회원가입 페이지 alert 등 알림 react-hot-toast의 토스트로 변경
- 로그인 페이지 alert 등 알림 react-hot-toast의 토스트로 변경
2023.11.29

💄 [Design] 알림 react-hot-toast로 변경 #102

---

open-market/src/pages/MyPage.tsx
open-market/src/pages/UserProducts.tsx
open-market/src/routes.tsx

- 라우터 동적경로로 수정
- 판매 상품관리 데이터 연동
- 내 판매상품 관리 조회 기능 구현
2023.11.29

✨ [Feature] 내 판매 상품 조회 기능 구현 #100

---

open-market/src/pages/ProductEdit.tsx

:sparkles: [Feature] 상품 수정 기능 구현 #111

---

open-market/src/layout/Header.tsx

- 로그인한 상태면 마이페이지 버튼 옆 로그아웃 버튼이 보이게끔 구성
- 로그아웃 버튼 클릭시 로컬스토리지 토큰 제거
- 전역 관리중인 로그인 상태 초기화
- 홈페이지로 리디렉션
- 로그아웃 여부를 알리는 토스트 알림 추가 예정
2023.11.30

✨[Feat] 로그아웃 기능 생성

---

open-market/src/order.d.ts
open-market/src/pages/Detail.tsx
open-market/src/pages/Purchase.tsx
open-market/src/product.d.ts
open-market/src/user.d.ts

- 댓글을 작성하기 위한 조건인 상품 구매 확인을 위해 상품 구매 시 유저에 order 속성 추가 기능 구현
- 로그인 한 유저의 이메일을 보여주기 위해 로그인 유저의 정보를 구하는 기능 구현
- 인터페이스 수정
- 댓글을 작성하는 기능 구현에서 에러가 발생하여 댓글을 작성하는 기능을 제외하고 우선 커밋함
2023.11.30

✨[Feature] 상품 구매 시 user order 수정 및 타입 변경 #99

---

open-market/src/pages/product/ProductDetail.tsx
open-market/src/pages/product/ProductEdit.tsx
open-market/src/pages/product/ProductRegistration.tsx
open-market/src/pages/user/SignIn.tsx
open-market/src/pages/user/SignUp.tsx
open-market/src/utils/debounce.ts
open-market/src/utils/index.ts

- debounce 함수 생성
- index.ts 파일 생성
- debounce 함수 적용
2023.12.05

:sparkles: [Feature] debounce 함수 적용 #157

---

open-market/src/pages/product/Productpurchase.tsx
open-market/src/routes.tsx

- Productpurchase 파스칼케이스로 수정
- user updtate url 수정
2023.12.05

:recycle:[Refactor] Productpurchase 파스칼케이스로 수정 및 user updtate url 수정 #155

---

open-market/src/pages/Index.tsx
open-market/src/pages/product/Productpurchase.tsx
open-market/src/routes.tsx
open-market/src/utils/filterProductList.ts
open-market/src/utils/index.ts

- 키워드 검색 시 name, category, tags 항목에 키워드가 포함된 상품이 나오도록 함수 구현
- 구현한 함수를 유틸함수로 이동
2023.12.06

✨[Feature] 인덱스 페이지에서 상품 검색 기능 구현 #171

---

open-market/src/pages/user/MyPage.tsx

- 기존의 회원 extra 조회하여 가져오던 북마크 정보를 api 변경으로 인해 기존 코드 삭제 후 새로운 호출 코드 작성
- 판매상품관리 부분, 판매 상품이 없을 시 "판매 내역이 없습니다." 라고 표시 되게끔 수정.
- 
```
async function fetchBookmarks() {
try {
const response = await axiosInstance.get(`/bookmarks`, {
headers: {
Authorization: `Bearer ${accessToken}`,
},
});
// console.log(response.data.item);
setBookmarkDetails(response.data.item || []);
} catch (error) {
console.error("북마크 정보 조회 실패:", error);
}
}
```
```
<article>
<h3>북마크</h3>
<ul>
{bookmarkDetails.length !== 0 ? (
bookmarkDetails.slice(0, 4).map((item) => (
<li key={item._id}>
<Link to={`/productdetail/${item.product_id}`}>
</Link>
</li>
))
) : (
<span>북마크가 없습니다.</span>
)}
</ul>
<Link to="/">전체보기</Link>
</article>
```
- pc 오작동으로 인한 코드 재작성
2023.12.06

🐛[Fix] api 변경으로 인한 MyPage에서 bookmark 호출 코드 수정 #161

---

open-market/src/pages/user/UserProducts.tsx
open-market/src/utils/index.ts
open-market/src/utils/itemWithExpireTime.ts
open-market/src/utils/numberWithComma.ts
samples/dbinit.js

- 내 판매상품 수익순으로 정렬하기
- numberWithComma 유틸함수 생성
- itemWithExpireTime 유틸함수 생성
- dbinit 데이터 수정
2023.12.06

✨ [Feature] 상품리스트를 수익순으로 정렬하는 기능 구현 #172

---

open-market/src/pages/Index.tsx
open-market/src/utils/filterProductList.ts

- searchProductList 함수의 searchKeword를 searchKeyword로 수정
- index.ts의 useState searchKeword를 searchKeyword로 수정
2023.12.06

:truck:[Rename] searchKeword를 searchKeyword로 수정 #181

---

open-market/src/layout/Header.tsx
open-market/src/main.tsx
open-market/src/pages/Index.tsx
open-market/src/states/productListState.ts

- productList와 searchKeyword, searchedList를 전역 상태로 관리하도록 수정
- 헤더에서 입력한 경우, 헤더 인풋 창은 빈 값이 되고 index의 검색창에 searchKeyword가 입력되도록 구현
- main.tsx에 React.Suspense fallback 추가
- 키 다운 이벤트로 인해 발생한 오류 해결
#183
#187
- 리코일로 상태 관리를 함에 따라 상품을 업로드 했을 때 reload하지 않으면 리스트에 반영이 안되는 문제 발생 -> react query refetch이용하여 문제 해결
2023.12.07

✨[Feature] 헤더 검색 기능 구현 #176

---

open-market/src/pages/product/ProductDetail.tsx
open-market/src/pages/user/MyPage.tsx

- sessionStorage에 historylist 저장
- 마이페이지에서 내역 불러오기
2023.12.07

✨ [Feature] 히스토리 기능 구현 #195

---

open-market/src/interfaces/order.d.ts
open-market/src/interfaces/product.d.ts
open-market/src/pages/Index.tsx
open-market/src/pages/product/ProductDetail.tsx
open-market/src/pages/product/ProductManage.tsx
open-market/src/pages/product/ProductPurchase.tsx
open-market/src/pages/user/MyPage.tsx
open-market/src/pages/user/UserOrders.tsx
open-market/src/pages/user/UserProducts.tsx
open-market/src/utils/filterProductList.ts

- image, sound file 관련 타입 생성 및 적용
- orderProduct 타입 생성 및 적용
- main images, sound file src 수정
현재 강사님의 db로 작업 중. 이 db에는 sound file과 category가 없는 항목이 있어서 옵셔널로 되어있지만, 추후에는 이 부분은 삭제해도 될 것 같음
2023.12.11

♻️[Refactor] API 수정에 따른 mainImages 타입 및 코드 수정 #212

---

open-market/src/pages/product/ProductDetail.tsx

- API 수정으로 a 태그를 이용하여 다운로드 기능 구현
2023.12.11

:sparkles:[Feature] 음원 다운로드 기능 구현 #202

---

open-market/src/pages/product/ProductEdit.tsx
open-market/src/pages/product/ProductRegistration.tsx
open-market/src/utils/uploadFile.ts
samples/dbinit.js

- uploadFile 수정
- 상품등록 및 수정 페이지 코드 수정
2023.12.11

:recycle: [Refactor] api 수정에 따른 코드 수정 #211

---

open-market/src/components/AuthInput.tsx
open-market/src/layout/AuthLayout.tsx
open-market/src/layout/RootLayout.tsx
open-market/src/pages/user/SignIn.tsx
open-market/src/pages/user/SignUp.tsx

- 로그인, 회원가입 페이지에서 공통으로 사용할 AuthInput 컴포넌트 생성, 사용
- 로그인 페이지 스타일링
- 회원가입 페이지 스타일링
2023.12.12

🎨[Design] 로그인, 회원가입 페이지 스타일링 #214

---

open-market/src/components/FormInput.tsx
open-market/src/components/FunctionalButton.tsx
open-market/src/components/SelectGenre.tsx
open-market/src/pages/product/ProductEdit.tsx
open-market/src/pages/product/ProductRegistration.tsx
open-market/src/utils/uploadFile.ts
samples/dbinit.js

- FormInput 컴포넌트 분리 및 스타일링
- uploadFile 타입변경
- 장르 선택 컴포넌트 분리
2023.12.13

🐛 [Fix] defaultChecked로 했을 때 checked 상태가 변경되지 않는 버그 수정

---

open-market/src/components/ProductListItem.tsx
open-market/src/components/listMusicPlayer/ControlPanel.tsx
open-market/src/components/listMusicPlayer/MusicPlayer.tsx
open-market/src/components/listMusicPlayer/PlayerSlider.tsx
open-market/src/interfaces/order.d.ts
open-market/src/pages/Index.tsx
open-market/src/pages/user/UserOrders.tsx

- 뮤직 플레이어 커스텀
- 상품 리스트 컴포넌트 생성
- 인덱스 페이지와 구매내역 페이지 내에서 다르게 보이도록 구현(다운로드 버튼)
인덱스 페이지
구매내역 페이지
unique key 에러 해결 필요
2023.12.13

💄[Design] 상품 리스트 컴포넌트 생성 및 스타일링 #216

---

open-market/src/components/MyPageList.tsx
open-market/src/pages/user/MyPage.tsx

- 마이페이지 북마크, 히스토리, 구매내역, 판매 상품 관리 공통으로 사용할 수 있는 컴포넌트(MyPageList.tsx) 구성.
- 마이페이지에 해당 컴포넌트(MyPageList.tsx) 적용.
- MyPageList.tsx 컴포넌트 스타일링.
- 마이페이지 스타일링.
- 현재 디자인에 맞춰 main 섹션의 너비를 1440픽셀로 잡아둠.
- 해상도가 높은 모니터 혹은 넓은 화면에서의 좌우 공백 해결 필요.
- 픽셀에 의존한 스타일링으로 차후 개선 여지가 있을 것으로 보임.
2023.12.13

♻️[Refactor] 마이페이지 북마크, 히스토리, 구매내역, 판매 상품 관리 공통 사용 사용 컴포넌트 구성 및 스타일링 #220

---

open-market/src/components/FormInput.tsx
open-market/src/components/FunctionalButton.tsx
open-market/src/components/SelectGenre.tsx
open-market/src/components/Textarea.tsx
open-market/src/pages/product/ProductRegistration.tsx
open-market/src/styles/common.ts
open-market/src/utils/uploadFile.ts

- 상품등록페이지 레이아웃 및 스타일링
- spacingXl: "30px"추가
- SelectGenre 스타일링
- Textarea 컴포넌트 생성 및 스타일링
-  interface 생성
2023.12.14

💄 [Design] 상품등록페이지 레이아웃 및 스타일링 #218

---

open-market/src/pages/product/ProductEdit.tsx
open-market/src/pages/product/ProductRegistration.tsx

- 상품 수정 페이지 레이아웃 구성
- 상품 수정 페이지 수정
- 음원 올린 후 레이아웃 수정
2023.12.14

💄 [Design] 상품 수정 페이지 레이아웃 구성 및 스타일링 #228

---

open-market/src/components/FilterComponent.tsx
open-market/src/components/SearchBar.tsx
open-market/src/interfaces/order.d.ts
open-market/src/pages/Index.tsx
open-market/src/pages/user/UserOrders.tsx
open-market/src/pages/user/UserProducts.tsx
open-market/src/utils/filterProductList.ts
open-market/src/utils/itemWithExpireTime.ts

- SearchBar 컴포넌트 생성 및 적용
- FilterComponent 생성 및 sort button, select에 적용 
- 구매내역 페이지 검색 기능 구현
2023.12.14

💄[Deisgn] searchbar, filter 컴포넌트 생성 및 스타일링 #224

---

open-market/src/layout/Footer.tsx
open-market/src/layout/Header.tsx

- 헤더 스타일링
- 푸터 스타일링
- 헤더 검색 컴포넌트 검색 버튼으로도 겁색 가능하게끔 기능 추가.
2023.12.14

💄[Design] 헤더 및 푸터 스타일링 #226

---

open-market/src/components/Textarea.tsx
open-market/src/pages/product/ProductDetail.tsx
open-market/src/pages/product/ProductManage.tsx
open-market/src/pages/product/ProductRegistration.tsx

- 등록 페이지 레이아웃 수정
-  상품 디테일에서 줄바꿈되지 않는 현상 수정
- 상품관리 페이지 레이아웃 구성 및 스타일링
2023.12.14

💄 [Design] 상품관리 페이지 레이아웃 구성 및 스타일링 #230

---

open-market/src/layout/Footer.tsx
open-market/src/layout/Header.tsx

- footer 코드중 원인이 되는 hover 시 밑줄을 생기게 하는 코드 제거
2023.12.14

🐛[Fix] hover 시 전체 영역에 밑줄이 생기는 버그 해결 #235

---

open-market/src/components/FilterComponent.tsx
open-market/src/components/ProductListComponent.tsx
open-market/src/components/ProductListItem.tsx
open-market/src/components/SearchBar.tsx
open-market/src/components/listMusicPlayer/ControlPanel.tsx
open-market/src/components/listMusicPlayer/MusicPlayer.tsx
open-market/src/components/listMusicPlayer/PlayerSlider.tsx
open-market/src/pages/user/UserOrders.tsx

- 구매내역 페이지 스타일 작업
- 재사용성이 높은 코드는 ProdudctListComponent.tsx로 별도 분리
2023.12.14

💄[Design] 구매내역 페이지 스타일 작업 #232

---

open-market/src/components/FilterComponent.tsx
open-market/src/components/ProductListItem.tsx
open-market/src/components/SearchBar.tsx
open-market/src/components/listMusicPlayer/ControlPanel.tsx
open-market/src/components/listMusicPlayer/MusicPlayer.tsx
open-market/src/components/listMusicPlayer/PlayerSlider.tsx
open-market/src/pages/Index.tsx
open-market/src/pages/user/UserOrders.tsx
open-market/src/pages/user/UserProducts.tsx

- 판매 상품 관리 리스트 컴포넌트 생성
- Music Player 관련 컴포넌트 display, width를 props로 전달받도록 수정
- 판매 상품 관리 페이지 스타일 작업
- searchbar, category filter props 전달 방식 수정
2023.12.15

💄[Design] 판매 상품 관리 페이지 스타일 작업 #241

---

open-market/src/components/FormInput.tsx
open-market/src/components/Textarea.tsx
open-market/src/pages/product/ProductManage.tsx
open-market/src/pages/product/ProductPurchase.tsx

- 상품 구매 페이지 레이아웃 구성
- 상품 구매 페이지 스타일링
- 타입에 따른 스타일 변화 (FormInput / Textarea)
2023.12.15

💄 [Design] 상품 구매 페이지 레이아웃 구성 및 스타일링e #236

---

open-market/src/components/ProductListItem.tsx
open-market/src/pages/product/ProductDetail.tsx
samples/dbinit.js

- api 수정에 따른 dbinit 수정
- 파일 다운로드 경로 수정
2023.12.15

♻️[Refactor] API 변경에 따른 db 수정 및 파일 경로 수정 #243 

---

open-market/src/components/ProductListItem.tsx

- ProductListItem unique key error 수정
2023.12.15

:bug: [Fix] ProductListItem unique key error 수정 #221

---

open-market/src/components/CommentComponent.tsx
open-market/src/components/ReplyComponent.tsx
open-market/src/pages/product/ProductDetail.tsx

- 댓글 관련 컴포넌트 생성 및 스타일 작업
추후 함수 수정 및 컴포넌트 수정 필요 (이슈 작성 완료)
ref 타입 에러 수정 필요 (이슈 작성 완료)
2023.12.17

💄[Design] 댓글 컴포넌트 생성 및 스타일 작업 #246 

---

open-market/src/components/ProductListItem.tsx
open-market/src/interfaces/product.d.ts
open-market/src/pages/product/ProductDetail.tsx
open-market/src/pages/product/ProductEdit.tsx
open-market/src/pages/product/ProductManage.tsx
open-market/src/pages/product/ProductPurchase.tsx
open-market/src/pages/product/ProductRegistration.tsx
open-market/src/pages/user/MyPage.tsx
open-market/src/utils/uploadFile.ts
samples/dbinit.js

- api 변경에 따른 파일 깨짐 수정
2023.12.17

🐛 [Fix] api 변경에 따른 파일 깨짐 수정 #256

---

open-market/public/loadingSpinner.svg
open-market/src/components/ProductListItem.tsx
open-market/src/components/UploadLoadingSpinner.tsx
open-market/src/components/listMusicPlayer/MusicPlayer.tsx
open-market/src/interfaces/product.d.ts
open-market/src/pages/product/ProductEdit.tsx
open-market/src/pages/product/ProductRegistration.tsx
open-market/src/utils/uploadFile.ts

- 배포 후 뮤직 플레이어 에러 해결 -> 로드 시간이 딜레이 됨에 따라 발생한 에러. 상품을 등록할 때 음원의 duration을 extra로 저장하여 그 값을 불러오도록 함
- 등록/수정 시 파일 업로드 상태에 따라 로딩 스피너 표기
기존의 상품은 extra.duration이 없기 때문에 00:00으로 표기. db 초기화 필요
2023.12.19

:recycle:[Refactor] 배포 후 뮤직 플레이어 에러 및 상품 등록/수정 시 파일 업로드 상태에 따라 로딩 스피너 표기 #259

---

open-market/src/pages/product/ProductDetail.tsx

- useRef TextArea 타입 에러 해결
타입을 위처럼 수정해서 에러 해결
ref를 주석처리한 경우 새로고침이 되지 않아 댓글이 자동으로 화면에 반영되지 않음
ref를 사용하지 않는 경우 textarea를 비우는 데에 문제 발생
Intersection Types으로 정의하여 문제 해결
2023.12.19

:bug:[Fix] useRef TextArea 타입 에러 해결 #246 #252

---

open-market/package-lock.json
open-market/package.json
open-market/src/App.tsx
open-market/src/layout/Header.tsx
open-market/src/pages/user/MyPage.tsx
open-market/src/pages/user/SignUp.tsx

- 마이페이지 리액트 쿼리 도입
- 사용 컴포넌트 별 로딩 중 MUI Skeleton 표시 기능 추가
- 기존 마이페이지와, 메인페이지 통합 이슈를 분할, 해당 PR 검토 후 이상 존재시 수정 후 메인페이지 리팩토링때 적용할 예정.
2023.12.20

♻️[Refactor] 마이페이지 컴포넌트 리액트 쿼리 도입 및 MUI 스켈레톤 적용 #264, #263

---

open-market/index.html
open-market/src/components/MyPageList.tsx
open-market/src/components/ProductDetailComponent.tsx
open-market/src/components/ProductListComponent.tsx
open-market/src/layout/Header.tsx
open-market/src/pages/Index.tsx
open-market/src/pages/product/ProductDetail.tsx
open-market/src/pages/product/ProductEdit.tsx
open-market/src/pages/product/ProductManage.tsx
open-market/src/pages/product/ProductPurchase.tsx
open-market/src/pages/product/ProductRegistration.tsx
open-market/src/pages/user/MyPage.tsx

- index.html 전체 배경색 적용
- 헤더 스크롤 상단 고정 및 z-index로 레이어링
- 마이페이지 Link 글자 색상 변경
- 전체 레이아웃이 틀어짐에 따라 헤더 사용 페이지 전부 스타일 조정
- 메인 페이지의 경우 ProductListComponent 컴포넌트에 적용한 스타일 때문에 배너와 리스트의 간격이 벌어짐
- 눈에 띄는 부분은 아니라는 판단 아래 차후 조정 예정
2023.12.20

💄[Design] 헤더 스타일 변경 및 페이지 레이아웃 스타일링 변경 #276

---

open-market/src/components/ProductDetailBadgeComponent.tsx
open-market/src/components/ProductListItem.tsx
open-market/src/components/listMusicPlayer/MusicPlayer.tsx
open-market/src/pages/product/ProductDetail.tsx
open-market/src/pages/product/ProductPurchase.tsx

- 이미 구매한 상품인 경우 url 접근 불가하게 하기
- 내가 등록한 상품인 경우 url 접근 불가하게 하기
- productDetail, productpurchase 접근 시 404 에러처리 (현재는 undefined로 나와있음)
- getOrder 함수 이름 변경 및 userOrder 타입 변경
- productDetail 페이지에서 fetchOrder 함수 실행 조건 변경
- PlayerContainer 오타 수정
- productpurchase에서 조건 처리 중 alt 표기 수정(안나오도록 수정)
- 파일 다운로드 링크 수정
- 37 : 내가 등록한 상품
- 28 : 이미 구매한 상품
- 100 : 존재하지 않는 상품
2023.12.21

♻️[Refactor] 상품 구매 페이지 리팩토링 #272

---

open-market/package-lock.json
open-market/package.json
open-market/src/components/ReplyComponent.tsx
open-market/src/pages/product/ProductDetail.tsx
open-market/src/pages/user/UserEdit.tsx

- getRating 함수 lodash 사용으로 수정
- 유저 프로필 사진 변경 시 저장된 currentUser에 변경되도록 수정
- Reply textarea background-color 수정
2023.12.21

♻️ [Refactor] reply 관련 로직 수정 #281

---

open-market/src/pages/product/ProductDetail.tsx
open-market/src/pages/product/ProductEdit.tsx
open-market/src/pages/product/ProductManage.tsx
open-market/src/pages/product/ProductPurchase.tsx
open-market/src/pages/product/ProductRegistration.tsx
open-market/src/pages/user/MyPage.tsx
open-market/src/pages/user/UserEdit.tsx
open-market/src/pages/user/UserOrders.tsx
open-market/src/pages/user/UserProducts.tsx
open-market/src/utils/refreshToken.ts
open-market/src/utils/uploadFile.ts

- axiosInstance 공통 헤더및 요청 인터셉터를 이용한 코드 간결화
- 강사님 피드백의 코드 활용
- 기존 axiosInstance 활용 부분에서 불필요한 헤더 모두 제거
- 요청 인터셉터에 엑세스 토큰 탑재로 인한 엑세스 토큰 저장 변수 제거
```
// axios 공통 설정
export const axiosInstance = axios.create({
baseURL: API_KEY,
timeout: 1000 * 5, // 5초 타임아웃
headers: {
"Content-Type": "application/json",
accept: "application/json", // 응답받고 싶은 데이터 타입
},
});
```
```
// 요청 인터셉터
axiosInstance.interceptors.request.use(
(config) => {
const token = localStorage.getItem("accessToken");
if (token) {
config.headers["Authorization"] = `Bearer ${token}`;
}
return config;
},
(error) => {
console.error("interceptors error", error);
return Promise.reject(error);
},
);
```
- axiosInstance 활용 부분이 많았던 만큼 테스트에 빈틈이 없었는지 확인 필요.
2023.12.21

♻️[Refactor] 토큰 갱신 유틸(axiosInstance) 공통 헤더 설정 #284

---

open-market/src/components/ProductListItem.tsx
open-market/src/components/ReplyComponent.tsx
open-market/src/hooks/useRequireAuth.ts
open-market/src/layout/Header.tsx
open-market/src/pages/product/ProductDetail.tsx
open-market/src/pages/product/ProductEdit.tsx
open-market/src/pages/product/ProductManage.tsx
open-market/src/pages/product/ProductPurchase.tsx
open-market/src/pages/product/ProductRegistration.tsx
open-market/src/pages/user/SignIn.tsx
open-market/src/pages/user/SignUp.tsx
open-market/src/pages/user/UserEdit.tsx
open-market/src/utils/refreshToken.ts
open-market/src/utils/uploadFile.ts

- 토스트 코드, 멘트 통일
- 상품 가격 입력 시 음수 막기
- 상품 관리 페이지에서 상품 상세 페이지 이동가능 하게 수정
- 상품 관리 페이지 말고 판매내역 리스트에서도 상품 공개/비공개 여부 확인 가능하게
- 구매페이지 셀러 아이디가 아닌 셀러 이름 표기
- textarea 크기 지정
- 상품 관리 페이지에서 판매내역 리스트로 이동 가능하게 링크 추가
- 회원가입, 수정 페이지 레이아웃 수정
- 14세 이상 동의 true인 경우 더 이상 체크박스 보여주지 않도록 수정
2023.12.21

♻️ [Refactor] 세부 리팩토링 #287 #283

---

open-market/src/pages/Index.tsx
open-market/src/pages/product/ProductDetail.tsx
open-market/src/pages/product/ProductEdit.tsx
open-market/src/pages/product/ProductManage.tsx
open-market/src/pages/product/ProductPurchase.tsx
open-market/src/pages/product/ProductRegistration.tsx
open-market/src/pages/user/SignIn.tsx
open-market/src/pages/user/SignUp.tsx
open-market/src/pages/user/UserEdit.tsx

- 회원가입, 유저정보 수정 페이지 레이아웃 깨짐 수정 #292 
2023.12.22

💄[Design] 회원가입, 유저정보 수정 페이지 레이아웃 깨짐 수정 #292 
